name: Linux

# https://docs.github.com/en/actions/how-tos/write-workflows/choose-when-workflows-run/control-workflow-concurrency
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ master, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 3

    steps:
    - uses: actions/checkout@v6.0.2

    - name: setup dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake cmake-extras ccache qt6-base-dev qt6-tools-dev-tools libqt6svg6 qt6-declarative-dev libx11-xcb1 libxkbcommon-dev
        
    - name: ccache timestamp
      id: ccache_cache_timestamp
      shell: cmake -P {0}
      run: |
        string(TIMESTAMP current_date "%Y-%m-%d-%H;%M;%S" UTC)
        message("::set-output name=timestamp::${current_date}")
        
    - name: ccache files
      uses: actions/cache@v5.0.5
      with:
        path: .ccache
        key: qtmvvm-ubuntu-ccache-${{ steps.ccache_cache_timestamp.outputs.timestamp }}
        restore-keys: |
          qtmvvm-ubuntu-ccache-
          
    - name: Build
      env:
        CCACHE_DIR: $GITHUB_WORKSPACE/.ccache
        CCACHE_COMPRESS: "true"
        CCACHE_COMPRESSLEVEL: "6"
        CCACHE_MAXSIZE: "400M"
        QT_QPA_PLATFORM: offscreen
      run: |
        mkdir $GITHUB_WORKSPACE/build
        cd $GITHUB_WORKSPACE/build
        cmake -G Ninja -DCMAKE_MAKE_PROGRAM=ninja -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DCMAKE_BUILD_TYPE=Release ../
        cmake --build . --config Release -j4

    - name: Upload tarball
      uses: actions/upload-artifact@v7
      if: success()
      with:
        name: qt-mvvm
        path: ./build/qt-mvvm-*.tar.gz  

    - name: Test
      env:
        QT_QPA_PLATFORM: offscreen
      run: |
        cd $GITHUB_WORKSPACE/build
        echo Running tests...
        ctest -j --quiet --output-on-failure
        echo Testing finished.

    - name: Upload test logs
      uses: actions/upload-artifact@v7
      if: failure()
      with:
        name: TestReport.log
        path: ./build/Testing/Temporary/LastTest.log
        retention-days: ${{ case(github.retention_days < 7, github.retention_days, 7) }}
        overwrite: true