name: TestCoverage

# https://docs.github.com/en/actions/how-tos/write-workflows/choose-when-workflows-run/control-workflow-concurrency
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

permissions:
  # `actions:write` permission is required to delete caches
  # See also: https://docs.github.com/en/rest/actions/cache?apiVersion=2022-11-28#delete-a-github-actions-cache-for-a-repository-using-a-cache-id
  actions: write
  contents: read

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ master, develop ]

jobs:

  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 3

    env:
      CCACHE_CACHE_KEY: ${{ github.workflow }}-ccache
      
    steps:

    - name: Checkout code
      uses: actions/checkout@v6.0.2

    - name: Install dependencies
      uses: awalsh128/cache-apt-pkgs-action@v1.6.1
      with:
        packages: build-essential cmake cmake-extras ccache qt6-base-dev qt6-tools-dev-tools libqt6svg6 qt6-declarative-dev libx11-xcb1 libxkbcommon-dev lcov
        version: 1.0
        execute_install_scripts: true

    - name: Restore the ccache
      id: restore-ccache
      uses: actions/cache/restore@v5
      with:
        key: ${{ env.CCACHE_CACHE_KEY }}
        path: ${{ github.workspace }}/.ccache
          
    - name: Build
      env:
        CCACHE_DIR: $GITHUB_WORKSPACE/.ccache
        CCACHE_COMPRESS: "true"
        CCACHE_COMPRESSLEVEL: "6"
        CCACHE_MAXSIZE: "400M"
        QT_QPA_PLATFORM: offscreen
      run: |
        mkdir $GITHUB_WORKSPACE/build
        cd $GITHUB_WORKSPACE/build
        cmake -G Ninja -DCMAKE_MAKE_PROGRAM=ninja -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DCMAKE_BUILD_TYPE=Profile ../
        cmake --build . --config Profile -j4

    - name: Delete the previously saved ccache
      continue-on-error: true
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GH_REPO: ${{ github.repository }}
      if: steps.restore-ccache.outputs.cache-hit == 'true'
      run: |
        echo "Deleting saved ccache keys..."
        gh cache delete ${{ env.CCACHE_CACHE_KEY }} --ref ${{ github.ref }}

    - name: Save the ccache
      if: always()
      uses: actions/cache/save@v5
      with:
        key: ${{ env.CCACHE_CACHE_KEY }}
        path: ${{ github.workspace }}/.ccache

    - name: Test
      env:
        QT_QPA_PLATFORM: offscreen        
      run: |
        cd $GITHUB_WORKSPACE/build
        echo Running tests...
        ctest -j --quiet --output-on-failure
        echo Testing finished.

    - name: Upload test logs
      uses: actions/upload-artifact@v7
      if: failure()
      with:
        name: TestReport.log
        path: ./build/Testing/Temporary/LastTest.log
        retention-days: ${{ case(github.retention_days < 7, github.retention_days, 7) }}
        overwrite: true

    - name: Generate test coverage summary
      run: |
        cd $GITHUB_WORKSPACE/build

        lcov --rc geninfo_unexecuted_blocks=1 --capture --directory . --output-file coverage.info --ignore-errors inconsistent --ignore-errors unused --include "$GITHUB_WORKSPACE/build/source/*" --parallel 4
        SUMMARY=$(lcov --summary coverage.info --ignore-errors format,format --ignore-errors inconsistent,inconsistent)
        echo "$SUMMARY"

        if echo "$SUMMARY" | grep "lines" | grep -q "no data found"; then
        LINES_PERCENT=0
        LINES_HIT=0
        LINES_TOTAL=0
        else
        LINES_PERCENT=$(echo "$SUMMARY" | grep "lines" | grep -oP '\K[0-9.]+(?=%)')
        LINES_HIT=$(echo "$SUMMARY" | grep "lines" | grep -oP '\(\K[0-9]+(?= of)')
        LINES_TOTAL=$(echo "$SUMMARY" | grep "lines" | grep -oP 'of \K[0-9]+(?= lines)')
        fi

        echo "LCOV_LINES_HIT=$LINES_HIT" >> $GITHUB_ENV
        echo "LCOV_LINES_TOTAL=$LINES_TOTAL" >> $GITHUB_ENV
        echo "LCOV_LINES_PERCENT=$LINES_PERCENT" >> $GITHUB_ENV

        if echo "$SUMMARY" | grep "functions" | grep -q "no data found"; then
        FUNCTIONS_PERCENT="0"
        FUNCTIONS_HIT="0"
        FUNCTIONS_TOTAL="0"
        else
        FUNCTIONS_PERCENT=$(echo "$SUMMARY" | grep "functions" | grep -oP '\K[0-9.]+(?=%)')
        FUNCTIONS_HIT=$(echo "$SUMMARY" | grep "functions" | grep -oP '\(\K[0-9]+(?= of)')
        FUNCTIONS_TOTAL=$(echo "$SUMMARY" | grep "functions" | grep -oP 'of \K[0-9]+(?= functions)')
        fi
        
        echo "LCOV_FUNCTIONS_HIT=$FUNCTIONS_HIT" >> $GITHUB_ENV
        echo "LCOV_FUNCTIONS_TOTAL=$FUNCTIONS_TOTAL" >> $GITHUB_ENV
        echo "LCOV_FUNCTIONS_PERCENT=$FUNCTIONS_PERCENT" >> $GITHUB_ENV
        
        echo "Lines:     $LINES_HIT / $LINES_TOTAL ($LINES_PERCENT%)"
        echo "Functions: $FUNCTIONS_HIT / $FUNCTIONS_TOTAL ($FUNCTIONS_PERCENT%)"
        
    - name: Generate test coverage report
      run: |
        cd $GITHUB_WORKSPACE/build
        genhtml --quiet --demangle-cpp --parallel --ignore-errors inconsistent --ignore-errors corrupt -o coverage -- coverage.info

    - name: Upload the test coverage report
      uses: actions/upload-artifact@v7
      with:
        name: TestCoverageReport
        path: ./build/coverage/
        retention-days: ${{ case(github.retention_days < 7, github.retention_days, 7) }}
        overwrite: true

    - name: Create coverage badges
      id: lines-coverage-badge
      uses: schneegans/dynamic-badges-action@v1.8.0
      with:
        auth: ${{ secrets.BADGE_GIST_SECRET }}
        gistID: ${{ vars.BADGE_GIST_ID }}
        filename: coverage_lines_badge.svg
        label: 'Coverage: Lines'
        message: ${{ env.LCOV_LINES_HIT }} of ${{ env.LCOV_LINES_TOTAL }} (${{ env.LCOV_LINES_PERCENT }}%)
        valColorRange: ${{ env.LCOV_LINES_PERCENT }}
        minColorRange: 0
        maxColorRange: 100
      continue-on-error: true

    - name: Handle Failure
      if: steps.lines-coverage-badge.outcome != 'success'
      run: |
        msg="The badge creation failed!\nTypically this happens on a fork due to the associated gist for storing the badge files belonging to another repository.\nPlease create a gist for the current repository/fork and update the respective BADGE_GIST_SECRET and BADGE_GIST_ID for the repository.\nNote that the BADGE_GIST_ID is also hardcoded in the README.md file and must be manually updated there too.\nOtherwise the badges pertaining to another repository will be shown, with the values related to that repository!"
        msg="${msg//'\n'/'%0A'}"
        echo "::error::$msg"

    - name: Create coverage badges
      id: functions-coverage-badge
      uses: schneegans/dynamic-badges-action@v1.8.0
      with:
        auth: ${{ secrets.BADGE_GIST_SECRET }}
        gistID: ${{ vars.BADGE_GIST_ID }}
        filename: coverage_functions_badge.svg
        label: 'Coverage: Functions'
        message: ${{ env.LCOV_FUNCTIONS_HIT }} of ${{ env.LCOV_FUNCTIONS_TOTAL }} (${{ env.LCOV_FUNCTIONS_PERCENT }}%)
        valColorRange: ${{ env.LCOV_FUNCTIONS_PERCENT }}
        minColorRange: 0
        maxColorRange: 100
      continue-on-error: true

    - name: Handle Failure
      if: steps.functions-coverage-badge.outcome != 'success'
      run: |
        msg="The badge creation failed!\nTypically this happens on a fork due to the associated gist for storing the badge files belonging to another repository.\nPlease create a gist for the current repository/fork and update the respective BADGE_GIST_SECRET and BADGE_GIST_ID for the repository.\nNote that the BADGE_GIST_ID is also hardcoded in the README.md file and must be manually updated there too.\nOtherwise the badges pertaining to another repository will be shown, with the values related to that repository!"
        msg="${msg//'\n'/'%0A'}"
        echo "::error::$msg"
